/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface Channel<RawValue extends Channel.RawValue = Channel.RawValue> {
  value: RawValue;
  visit: <Result>(visitor: Channel._Visitor<Result>) => Result;
}

const _Voice: Channel<"VOICE"> = {
  value: "VOICE",
  visit: (visitor) => visitor.voice(),
};
const _Push: Channel<"PUSH"> = {
  value: "PUSH",
  visit: (visitor) => visitor.push(),
};
const _Sms: Channel<"SMS"> = {
  value: "SMS",
  visit: (visitor) => visitor.sms(),
};
const _Email: Channel<"EMAIL"> = {
  value: "EMAIL",
  visit: (visitor) => visitor.email(),
};
const _Whatsapp: Channel<"WHATSAPP"> = {
  value: "WHATSAPP",
  visit: (visitor) => visitor.whatsapp(),
};
const _Webhook: Channel<"WEBHOOK"> = {
  value: "WEBHOOK",
  visit: (visitor) => visitor.webhook(),
};
const _Slack: Channel<"SLACK"> = {
  value: "SLACK",
  visit: (visitor) => visitor.slack(),
};
const _InApp: Channel<"IN_APP"> = {
  value: "IN_APP",
  visit: (visitor) => visitor.inApp(),
};
const _Telegram: Channel<"TELEGRAM"> = {
  value: "TELEGRAM",
  visit: (visitor) => visitor.telegram(),
};
export const Channel = {
  Voice: _Voice,
  Push: _Push,
  Sms: _Sms,
  Email: _Email,
  Whatsapp: _Whatsapp,
  Webhook: _Webhook,
  Slack: _Slack,
  InApp: _InApp,
  Telegram: _Telegram,
  _parse: (value: string): Channel => {
    switch (value) {
      case "VOICE": {
        return _Voice;
      }
      case "PUSH": {
        return _Push;
      }
      case "SMS": {
        return _Sms;
      }
      case "EMAIL": {
        return _Email;
      }
      case "WHATSAPP": {
        return _Whatsapp;
      }
      case "WEBHOOK": {
        return _Webhook;
      }
      case "SLACK": {
        return _Slack;
      }
      case "IN_APP": {
        return _InApp;
      }
      case "TELEGRAM": {
        return _Telegram;
      }
      default: {
        return {
          value: value as Channel.RawValue,
          visit: (visitor) => visitor._other(value),
        };
      }
    }
  },
} as const;

export declare namespace Channel {
  type RawValue = "VOICE" | "PUSH" | "SMS" | "EMAIL" | "WHATSAPP" | "WEBHOOK" | "SLACK" | "IN_APP" | "TELEGRAM";

  interface _Visitor<Result> {
    voice: () => Result;
    push: () => Result;
    sms: () => Result;
    email: () => Result;
    whatsapp: () => Result;
    webhook: () => Result;
    slack: () => Result;
    inApp: () => Result;
    telegram: () => Result;
    _other: (value: string) => Result;
  }
}
