/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";

export interface UserPreferences {
  preferredChannel?: RavenApi.user.Channel;
  channelPreferences?: RavenApi.user.ChannelPreferences;
}
