/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";

export interface UserPreferences {
  preferredChannel?: RavenApi.Channel;
  channelPreferences?: RavenApi.ChannelPreferences;
}
