/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";

export interface EmailOverride extends RavenApi.ChannelOverride {
  from: RavenApi.EmailRecipient;
  cc: RavenApi.EmailRecipient[];
  bcc: RavenApi.EmailRecipient[];
  attachments: RavenApi.Attachment[];
  message: RavenApi.EmailMessage;
}
