/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";

export interface ProviderOverride {
  payload: Record<string, unknown>;
  formParams: RavenApi.Param[];
  queryParams: RavenApi.Param[];
  pathParams: RavenApi.Param[];
  headers: RavenApi.Param[];
}
