/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";

export interface SendEventRequest {
  /** event name */
  event: string;
  /**
   * {
   * "param1" : "<value1>",
   * "param2" : "<value2>",
   * "param3" : object/array"
   * }
   *
   */
  data: Record<string, unknown>;
  user?: RavenApi.User;
  /**
   * Time to send message expressed as UTC milliseconds.
   * If not present, message will be sent immediately.
   *
   */
  scheduleAt?: number;
  override?: RavenApi.EventOverride;
}
