/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";

export interface SmsOverride extends RavenApi.event.ChannelOverride {
  sender: string;
  message: RavenApi.event.SmsMessage;
}
