/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";
import * as serializers from "../..";

export const ChannelPreferences: core.schemas.ObjectSchema<ChannelPreferences.Raw, RavenApi.ChannelPreferences> =
  core.schemas.object({
    sms: core.schemas.lazyObject(async () => (await import("../..")).ChannelPreference).optional(),
    push: core.schemas.lazyObject(async () => (await import("../..")).ChannelPreference).optional(),
    whatsapp: core.schemas.lazyObject(async () => (await import("../..")).ChannelPreference).optional(),
    email: core.schemas.lazyObject(async () => (await import("../..")).ChannelPreference).optional(),
    slack: core.schemas.lazyObject(async () => (await import("../..")).ChannelPreference).optional(),
    voice: core.schemas.lazyObject(async () => (await import("../..")).ChannelPreference).optional(),
    teams: core.schemas.lazyObject(async () => (await import("../..")).ChannelPreference).optional(),
  });

export declare namespace ChannelPreferences {
  interface Raw {
    sms?: serializers.ChannelPreference.Raw | null;
    push?: serializers.ChannelPreference.Raw | null;
    whatsapp?: serializers.ChannelPreference.Raw | null;
    email?: serializers.ChannelPreference.Raw | null;
    slack?: serializers.ChannelPreference.Raw | null;
    voice?: serializers.ChannelPreference.Raw | null;
    teams?: serializers.ChannelPreference.Raw | null;
  }
}
