/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const ChannelPreferences: core.schemas.ObjectSchema<ChannelPreferences.Raw, RavenApi.user.ChannelPreferences> =
  core.schemas.object({
    sms: core.schemas.lazyObject(() => serializers.user.ChannelPreference).optional(),
    push: core.schemas.lazyObject(() => serializers.user.ChannelPreference).optional(),
    whatsapp: core.schemas.lazyObject(() => serializers.user.ChannelPreference).optional(),
    email: core.schemas.lazyObject(() => serializers.user.ChannelPreference).optional(),
    slack: core.schemas.lazyObject(() => serializers.user.ChannelPreference).optional(),
    voice: core.schemas.lazyObject(() => serializers.user.ChannelPreference).optional(),
    teams: core.schemas.lazyObject(() => serializers.user.ChannelPreference).optional(),
  });

export declare namespace ChannelPreferences {
  interface Raw {
    sms?: serializers.user.ChannelPreference.Raw | null;
    push?: serializers.user.ChannelPreference.Raw | null;
    whatsapp?: serializers.user.ChannelPreference.Raw | null;
    email?: serializers.user.ChannelPreference.Raw | null;
    slack?: serializers.user.ChannelPreference.Raw | null;
    voice?: serializers.user.ChannelPreference.Raw | null;
    teams?: serializers.user.ChannelPreference.Raw | null;
  }
}
