/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";
import * as serializers from "../..";

export const RavenUser: core.schemas.ObjectSchema<RavenUser.Raw, RavenApi.RavenUser> = core.schemas.object({
  userId: core.schemas.property(
    "user_id",
    core.schemas.lazy(async () => (await import("../..")).UserId)
  ),
  userSid: core.schemas.property("user_sid", core.schemas.string().optional()),
  onesignalExternalId: core.schemas.property("onesignal_external_id", core.schemas.string().optional()),
  mobile: core.schemas.string().optional(),
  email: core.schemas.string().optional(),
  whatsappMobile: core.schemas.property("whatsapp_mobile", core.schemas.string().optional()),
  slack: core.schemas.lazyObject(async () => (await import("../..")).SlackProfile).optional(),
  telegram: core.schemas.lazyObject(async () => (await import("../..")).TelegramProfile).optional(),
  fcmTokens: core.schemas.property("fcm_tokens", core.schemas.list(core.schemas.string()).optional()),
  onesignalPlayerIds: core.schemas.property(
    "onesignal_player_ids",
    core.schemas.list(core.schemas.string()).optional()
  ),
  iosTokens: core.schemas.property("ios_tokens", core.schemas.list(core.schemas.string()).optional()),
  createdAt: core.schemas.property("created_at", core.schemas.number().optional()),
  updatedAt: core.schemas.property("updated_at", core.schemas.number().optional()),
});

export declare namespace RavenUser {
  interface Raw {
    user_id: serializers.UserId.Raw;
    user_sid?: string | null;
    onesignal_external_id?: string | null;
    mobile?: string | null;
    email?: string | null;
    whatsapp_mobile?: string | null;
    slack?: serializers.SlackProfile.Raw | null;
    telegram?: serializers.TelegramProfile.Raw | null;
    fcm_tokens?: string[] | null;
    onesignal_player_ids?: string[] | null;
    ios_tokens?: string[] | null;
    created_at?: number | null;
    updated_at?: number | null;
  }
}
