/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";

export const SlackProfile: core.schemas.ObjectSchema<SlackProfile.Raw, RavenApi.SlackProfile> = core.schemas.object({
  accessToken: core.schemas.property("access_token", core.schemas.string()),
  email: core.schemas.string().optional(),
  channelId: core.schemas.property("channel_id", core.schemas.string().optional()),
});

export declare namespace SlackProfile {
  interface Raw {
    access_token: string;
    email?: string | null;
    channel_id?: string | null;
  }
}
