/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";

export const TelegramProfile: core.schemas.ObjectSchema<TelegramProfile.Raw, RavenApi.user.TelegramProfile> =
  core.schemas.object({
    chatId: core.schemas.property("chat_id", core.schemas.string()),
  });

export declare namespace TelegramProfile {
  interface Raw {
    chat_id: string;
  }
}
