/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const UserPreferences: core.schemas.ObjectSchema<UserPreferences.Raw, RavenApi.user.UserPreferences> =
  core.schemas.object({
    preferredChannel: core.schemas.property(
      "preferred_channel",
      core.schemas.lazy(() => serializers.user.Channel).optional()
    ),
    channelPreferences: core.schemas.property(
      "channel_preferences",
      core.schemas.lazyObject(() => serializers.user.ChannelPreferences).optional()
    ),
  });

export declare namespace UserPreferences {
  interface Raw {
    preferred_channel?: serializers.user.Channel.Raw | null;
    channel_preferences?: serializers.user.ChannelPreferences.Raw | null;
  }
}
