/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Platform = "android" | "web" | "ios";

export const Platform = {
    Android: "android",
    Web: "web",
    Ios: "ios",
} as const;
