/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";
import * as serializers from "../..";

export const BatchEvent: core.schemas.ObjectSchema<BatchEvent.Raw, RavenApi.BatchEvent> = core.schemas.object({
  data: core.schemas.record(core.schemas.string(), core.schemas.unknown()),
  user: core.schemas.lazyObject(async () => (await import("../..")).User).optional(),
  override: core.schemas.lazyObject(async () => (await import("../..")).EventOverride).optional(),
});

export declare namespace BatchEvent {
  interface Raw {
    data: Record<string, unknown>;
    user?: serializers.User.Raw | null;
    override?: serializers.EventOverride.Raw | null;
  }
}
