/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const BulkSendEventRequest: core.schemas.ObjectSchema<
  BulkSendEventRequest.Raw,
  RavenApi.event.BulkSendEventRequest
> = core.schemas.object({
  event: core.schemas.string(),
  batch: core.schemas.list(core.schemas.lazyObject(() => serializers.event.BatchEvent)),
});

export declare namespace BulkSendEventRequest {
  interface Raw {
    event: string;
    batch: serializers.event.BatchEvent.Raw[];
  }
}
