/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";
import * as serializers from "../..";

export const BulkSendEventRequest: core.schemas.ObjectSchema<BulkSendEventRequest.Raw, RavenApi.BulkSendEventRequest> =
  core.schemas.object({
    event: core.schemas.string(),
    batch: core.schemas.list(core.schemas.lazyObject(async () => (await import("../..")).BatchEvent)),
  });

export declare namespace BulkSendEventRequest {
  interface Raw {
    event: string;
    batch: serializers.BatchEvent.Raw[];
  }
}
