/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";

export const ChannelOverride: core.schemas.ObjectSchema<ChannelOverride.Raw, RavenApi.ChannelOverride> =
  core.schemas.object({
    scheduleAt: core.schemas.property("schedule_at", core.schemas.number()),
  });

export declare namespace ChannelOverride {
  interface Raw {
    schedule_at: number;
  }
}
