/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";

export const EmailMessage: core.schemas.ObjectSchema<EmailMessage.Raw, RavenApi.EmailMessage> = core.schemas.object({
  text: core.schemas.string(),
  htmlBody: core.schemas.property("html_body", core.schemas.string()),
  subject: core.schemas.string(),
});

export declare namespace EmailMessage {
  interface Raw {
    text: string;
    html_body: string;
    subject: string;
  }
}
