/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";
import * as serializers from "../..";

export const EmailOverride: core.schemas.ObjectSchema<EmailOverride.Raw, RavenApi.EmailOverride> = core.schemas
  .object({
    from: core.schemas.lazyObject(async () => (await import("../..")).EmailRecipient),
    cc: core.schemas.list(core.schemas.lazyObject(async () => (await import("../..")).EmailRecipient)),
    bcc: core.schemas.list(core.schemas.lazyObject(async () => (await import("../..")).EmailRecipient)),
    attachments: core.schemas.list(core.schemas.lazyObject(async () => (await import("../..")).Attachment)),
    message: core.schemas.lazyObject(async () => (await import("../..")).EmailMessage),
  })
  .extend(core.schemas.lazyObject(async () => (await import("../..")).ChannelOverride));

export declare namespace EmailOverride {
  interface Raw extends serializers.ChannelOverride.Raw {
    from: serializers.EmailRecipient.Raw;
    cc: serializers.EmailRecipient.Raw[];
    bcc: serializers.EmailRecipient.Raw[];
    attachments: serializers.Attachment.Raw[];
    message: serializers.EmailMessage.Raw;
  }
}
