/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";

export const EmailRecipient: core.schemas.ObjectSchema<EmailRecipient.Raw, RavenApi.event.EmailRecipient> =
  core.schemas.object({
    name: core.schemas.string(),
    address: core.schemas.string(),
  });

export declare namespace EmailRecipient {
  interface Raw {
    name: string;
    address: string;
  }
}
