/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";
import * as serializers from "../..";

export const EventOverride: core.schemas.ObjectSchema<EventOverride.Raw, RavenApi.EventOverride> = core.schemas.object({
  email: core.schemas.lazyObject(async () => (await import("../..")).EmailOverride).optional(),
  sms: core.schemas.lazyObject(async () => (await import("../..")).SmsOverride).optional(),
  whatsapp: core.schemas.lazyObject(async () => (await import("../..")).WhatsappOverride).optional(),
  push: core.schemas.lazyObject(async () => (await import("../..")).PushOverride).optional(),
  webhook: core.schemas.lazyObject(async () => (await import("../..")).WebhookOverride).optional(),
  voice: core.schemas.lazyObject(async () => (await import("../..")).VoiceOverride).optional(),
  slack: core.schemas.lazyObject(async () => (await import("../..")).SlackOverride).optional(),
  inApp: core.schemas.property(
    "in_app",
    core.schemas.lazyObject(async () => (await import("../..")).InAppOverride).optional()
  ),
  telegram: core.schemas.lazyObject(async () => (await import("../..")).TelegramOverride).optional(),
  providers: core.schemas.record(
    core.schemas.string(),
    core.schemas.lazyObject(async () => (await import("../..")).ProviderOverride)
  ),
});

export declare namespace EventOverride {
  interface Raw {
    email?: serializers.EmailOverride.Raw | null;
    sms?: serializers.SmsOverride.Raw | null;
    whatsapp?: serializers.WhatsappOverride.Raw | null;
    push?: serializers.PushOverride.Raw | null;
    webhook?: serializers.WebhookOverride.Raw | null;
    voice?: serializers.VoiceOverride.Raw | null;
    slack?: serializers.SlackOverride.Raw | null;
    in_app?: serializers.InAppOverride.Raw | null;
    telegram?: serializers.TelegramOverride.Raw | null;
    providers: Record<string, serializers.ProviderOverride.Raw>;
  }
}
