/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const InAppOverride: core.schemas.ObjectSchema<InAppOverride.Raw, RavenApi.event.InAppOverride> = core.schemas
  .object({})
  .extend(core.schemas.lazyObject(() => serializers.event.ChannelOverride));

export declare namespace InAppOverride {
  interface Raw extends serializers.event.ChannelOverride.Raw {}
}
