/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";

export const Param: core.schemas.ObjectSchema<Param.Raw, RavenApi.Param> = core.schemas.object({
  name: core.schemas.string(),
  value: core.schemas.string(),
});

export declare namespace Param {
  interface Raw {
    name: string;
    value: string;
  }
}
