/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";
import * as serializers from "../..";

export const PushOverride: core.schemas.ObjectSchema<PushOverride.Raw, RavenApi.PushOverride> = core.schemas
  .object({})
  .extend(core.schemas.lazyObject(async () => (await import("../..")).ChannelOverride));

export declare namespace PushOverride {
  interface Raw extends serializers.ChannelOverride.Raw {}
}
