/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";
import * as serializers from "../..";

export const SendEventResponse: core.schemas.ObjectSchema<SendEventResponse.Raw, RavenApi.SendEventResponse> =
  core.schemas.object({
    id: core.schemas.lazy(async () => (await import("../..")).RequestId),
    success: core.schemas.boolean(),
  });

export declare namespace SendEventResponse {
  interface Raw {
    id: serializers.RequestId.Raw;
    success: boolean;
  }
}
