/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const SendEventRequest: core.schemas.ObjectSchema<SendEventRequest.Raw, RavenApi.event.SendEventRequest> =
  core.schemas.object({
    event: core.schemas.string(),
    data: core.schemas.record(core.schemas.string(), core.schemas.unknown()),
    user: core.schemas.lazyObject(() => serializers.event.User).optional(),
    scheduleAt: core.schemas.number().optional(),
    override: core.schemas.lazyObject(() => serializers.event.EventOverride).optional(),
  });

export declare namespace SendEventRequest {
  interface Raw {
    event: string;
    data: Record<string, unknown>;
    user?: serializers.event.User.Raw | null;
    scheduleAt?: number | null;
    override?: serializers.event.EventOverride.Raw | null;
  }
}
