/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";
import * as serializers from "../..";

export const SlackOverride: core.schemas.ObjectSchema<SlackOverride.Raw, RavenApi.SlackOverride> = core.schemas
  .object({
    message: core.schemas.lazyObject(async () => (await import("../..")).SlackMessage),
  })
  .extend(core.schemas.lazyObject(async () => (await import("../..")).ChannelOverride));

export declare namespace SlackOverride {
  interface Raw extends serializers.ChannelOverride.Raw {
    message: serializers.SlackMessage.Raw;
  }
}
