/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const SlackOverride: core.schemas.ObjectSchema<SlackOverride.Raw, RavenApi.event.SlackOverride> = core.schemas
  .object({
    message: core.schemas.lazyObject(() => serializers.event.SlackMessage),
  })
  .extend(core.schemas.lazyObject(() => serializers.event.ChannelOverride));

export declare namespace SlackOverride {
  interface Raw extends serializers.event.ChannelOverride.Raw {
    message: serializers.event.SlackMessage.Raw;
  }
}
