/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";

export const SmsMessage: core.schemas.ObjectSchema<SmsMessage.Raw, RavenApi.SmsMessage> = core.schemas.object({
  text: core.schemas.string(),
});

export declare namespace SmsMessage {
  interface Raw {
    text: string;
  }
}
