/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";
import * as serializers from "../..";

export const SmsOverride: core.schemas.ObjectSchema<SmsOverride.Raw, RavenApi.SmsOverride> = core.schemas
  .object({
    sender: core.schemas.string(),
    message: core.schemas.lazyObject(async () => (await import("../..")).SmsMessage),
  })
  .extend(core.schemas.lazyObject(async () => (await import("../..")).ChannelOverride));

export declare namespace SmsOverride {
  interface Raw extends serializers.ChannelOverride.Raw {
    sender: string;
    message: serializers.SmsMessage.Raw;
  }
}
