/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const SmsOverride: core.schemas.ObjectSchema<SmsOverride.Raw, RavenApi.event.SmsOverride> = core.schemas
  .object({
    sender: core.schemas.string(),
    message: core.schemas.lazyObject(() => serializers.event.SmsMessage),
  })
  .extend(core.schemas.lazyObject(() => serializers.event.ChannelOverride));

export declare namespace SmsOverride {
  interface Raw extends serializers.event.ChannelOverride.Raw {
    sender: string;
    message: serializers.event.SmsMessage.Raw;
  }
}
