/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";
import * as serializers from "../..";

export const TelegramOverride: core.schemas.ObjectSchema<TelegramOverride.Raw, RavenApi.TelegramOverride> = core.schemas
  .object({})
  .extend(core.schemas.lazyObject(async () => (await import("../..")).ChannelOverride));

export declare namespace TelegramOverride {
  interface Raw extends serializers.ChannelOverride.Raw {}
}
