/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";
import * as serializers from "../..";

export const VoiceOverride: core.schemas.ObjectSchema<VoiceOverride.Raw, RavenApi.VoiceOverride> = core.schemas
  .object({})
  .extend(core.schemas.lazyObject(async () => (await import("../..")).ChannelOverride));

export declare namespace VoiceOverride {
  interface Raw extends serializers.ChannelOverride.Raw {}
}
