/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const VoiceOverride: core.schemas.ObjectSchema<VoiceOverride.Raw, RavenApi.event.VoiceOverride> = core.schemas
  .object({})
  .extend(core.schemas.lazyObject(() => serializers.event.ChannelOverride));

export declare namespace VoiceOverride {
  interface Raw extends serializers.event.ChannelOverride.Raw {}
}
