/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";
import * as serializers from "../..";

export const WebhookOverride: core.schemas.ObjectSchema<WebhookOverride.Raw, RavenApi.WebhookOverride> = core.schemas
  .object({})
  .extend(core.schemas.lazyObject(async () => (await import("../..")).ChannelOverride));

export declare namespace WebhookOverride {
  interface Raw extends serializers.ChannelOverride.Raw {}
}
