/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../environments";
import * as core from "../../../core";
import { RavenApi } from "@ravenapp/raven";
import urlJoin from "url-join";
import * as serializers from "../../../serialization";

export declare namespace Client {
  interface Options {
    environment?: environments.Environment | string;
    auth?: {
      authorization?: core.Supplier<string>;
    };
  }
}

export class Client {
  constructor(private readonly options: Client.Options) {}

  public async send(request: RavenApi.event.send.Request): Promise<RavenApi.event.send.Response> {
    const response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.Environment.Prod, `/v1/apps/${request.appId}/events/send`),
      method: "POST",
      headers: {
        Authorization: await core.Supplier.get(this.options.auth?.authorization),
        "Idempotency-Key": request.idempotencyKey,
      },
      body: await serializers.SendEventRequest.json(request._body),
    });
    if (response.ok) {
      return {
        ok: true,
        body: await serializers.SendEventResponse.parse(response.body as serializers.SendEventResponse.Raw),
      };
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }

  public async sendBulk(request: RavenApi.event.sendBulk.Request): Promise<RavenApi.event.sendBulk.Response> {
    const response = await core.fetcher({
      url: urlJoin(
        this.options.environment ?? environments.Environment.Prod,
        `/v1/apps/${request.appId}/events/bulk_send`
      ),
      method: "POST",
      headers: {
        Authorization: await core.Supplier.get(this.options.auth?.authorization),
        "Idempotency-Key": request.idempotencyKey,
      },
      body: await serializers.BulkSendEventRequest.json(request._body),
    });
    if (response.ok) {
      return {
        ok: true,
        body: await serializers.SendEventResponse.parse(response.body as serializers.SendEventResponse.Raw),
      };
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }
}
