/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../environments";
import * as core from "../../../core";
import { RavenApi } from "@ravenapp/raven";
import urlJoin from "url-join";
import * as serializers from "../../../serialization";

export declare namespace Client {
  interface Options {
    environment?: environments.Environment | string;
    auth?: {
      authorization?: core.Supplier<string>;
    };
  }
}

export class Client {
  constructor(private readonly options: Client.Options) {}

  public async createOrUpdate(
    request: RavenApi.user.createOrUpdate.Request
  ): Promise<RavenApi.user.createOrUpdate.Response> {
    const response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.Environment.Prod, `/v1/apps/${request.appId}/users`),
      method: "POST",
      headers: {
        Authorization: await core.Supplier.get(this.options.auth?.authorization),
      },
      body: await serializers.CreateUserRequest.json(request._body),
    });
    if (response.ok) {
      return {
        ok: true,
        body: await serializers.RavenUser.parse(response.body as serializers.RavenUser.Raw),
      };
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }

  public async get(request: RavenApi.user.get.Request): Promise<RavenApi.user.get.Response> {
    const response = await core.fetcher({
      url: urlJoin(
        this.options.environment ?? environments.Environment.Prod,
        `/v1/apps/${request.appId}/users/${request.userId}`
      ),
      method: "GET",
      headers: {
        Authorization: await core.Supplier.get(this.options.auth?.authorization),
      },
    });
    if (response.ok) {
      return {
        ok: true,
        body: await serializers.RavenUser.parse(response.body as serializers.RavenUser.Raw),
      };
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }
}
