/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";

export interface Request {
  appId: RavenApi.AppId;
  _body: RavenApi.CreateUserRequest;
}

export type Response = core.APIResponse<RavenApi.RavenUser, RavenApi.user.createOrUpdate.Error>;
export type Error = RavenApi.user.createOrUpdate.Error._Unknown;

export declare namespace Error {
  interface _Unknown extends _Utils {
    errorName: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <_Result>(visitor: RavenApi.user.createOrUpdate.Error._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    _other: (value: core.Fetcher.Error) => _Result;
  }
}
