/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors";
import { RavenApi } from "@ravenapp/raven";

export class EventNotFoundError extends errors.RavenApiError {
    constructor(body: RavenApi.EventNotFoundErrorBody) {
        super({
            message: "EventNotFoundError",
            statusCode: 404,
            body: body,
        });
        Object.setPrototypeOf(this, EventNotFoundError.prototype);
    }
}
