/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";

export const DeviceId: core.schemas.Schema<DeviceId.Raw, RavenApi.DeviceId> = core.schemas.string();

export declare namespace DeviceId {
  type Raw = string;
}
