/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";

export const RequestId: core.schemas.Schema<RequestId.Raw, RavenApi.RequestId> = core.schemas.string();

export declare namespace RequestId {
  type Raw = string;
}
