/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";

export const UserId: core.schemas.Schema<UserId.Raw, RavenApi.ids.UserId> = core.schemas.string();

export declare namespace UserId {
  type Raw = string;
}
