/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";

export interface BatchEvent {
  /**
   * {
   * "param1" : "<value1>",
   * "param2" : "<value2>",
   * "param3" : object/array"
   * }
   *
   */
  data: Record<string, unknown>;
  user?: RavenApi.event.User;
  override?: RavenApi.event.EventOverride;
}
