/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";

export interface EmailOverride extends RavenApi.event.ChannelOverride {
  from: RavenApi.event.EmailRecipient;
  cc: RavenApi.event.EmailRecipient[];
  bcc: RavenApi.event.EmailRecipient[];
  attachments: RavenApi.event.Attachment[];
  message: RavenApi.event.EmailMessage;
}
