/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";

export interface EventOverride {
  email?: RavenApi.event.EmailOverride;
  sms?: RavenApi.event.SmsOverride;
  whatsapp?: RavenApi.event.WhatsappOverride;
  push?: RavenApi.event.PushOverride;
  webhook?: RavenApi.event.WebhookOverride;
  voice?: RavenApi.event.VoiceOverride;
  slack?: RavenApi.event.SlackOverride;
  inApp?: RavenApi.event.InAppOverride;
  telegram?: RavenApi.event.TelegramOverride;
  providers: Record<string, RavenApi.event.ProviderOverride>;
}
