/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";

export interface ProviderOverride {
  payload: Record<string, unknown>;
  formParams: RavenApi.event.Param[];
  queryParams: RavenApi.event.Param[];
  pathParams: RavenApi.event.Param[];
  headers: RavenApi.event.Param[];
}
