/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";

export interface User {
  /**
   * userId to send the notifications to.
   * This is  your own user identifier which you have used to create user on Raven
   *
   */
  userId: RavenApi.ids.UserId;
  email?: string;
  /** mobile with country code prefix (e.g +91) */
  mobile?: string;
  /**
   * mobile with country code prefix (e.g. +91).
   * if empty, `mobile` is considered for whatsapp
   *
   */
  whatsappMobile?: string;
  /** [OneSignal external user IDs](https://documentation.onesignal.com/docs/external-user-ids) */
  onesignalExternalId?: string;
  /** List of fcm tokens.  eg. ["<fcmtoken1", "<fcmtoken2>"] */
  fcmTokens?: string[];
}
