/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";

export interface WhatsappOverride extends RavenApi.event.ChannelOverride {
  message: RavenApi.event.SmsMessage;
}
