/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class RavenApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, RavenApiTimeoutError.prototype);
    }
}
