/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../core";

export const AppId: core.serialization.Schema<serializers.AppId.Raw, RavenApi.AppId> = core.serialization.string();

export declare namespace AppId {
    type Raw = string;
}
