/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../core";

export const DeviceId: core.serialization.Schema<serializers.DeviceId.Raw, RavenApi.DeviceId> =
    core.serialization.string();

export declare namespace DeviceId {
    type Raw = string;
}
