/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../core";

export const RequestId: core.serialization.Schema<serializers.RequestId.Raw, RavenApi.RequestId> =
    core.serialization.string();

export declare namespace RequestId {
    type Raw = string;
}
