/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as core from "../../../core";
import { RavenApi } from "../../..";

export interface Request {
  authorization?: core.Supplier<string>;
  appId: RavenApi.ids.AppId;
  _body: RavenApi.event.SendEventRequest;
}

export type Response = core.APIResponse<RavenApi.event.SendEventResponse, RavenApi.event.send.Error>;
export type Error = Error.EventNotFoundError | Error.EventNotPublishedError | Error._Unknown;

export declare namespace Error {
  interface EventNotFoundError extends _Utils {
    errorName: "EventNotFoundError";
  }

  interface EventNotPublishedError extends _Utils {
    errorName: "EventNotPublishedError";
  }

  interface _Unknown extends _Utils {
    errorName: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <Result>(visitor: Error._Visitor<Result>) => Result;
  }

  interface _Visitor<Result> {
    eventNotFoundError: () => Result;
    eventNotPublishedError: () => Result;
    _other: (value: core.Fetcher.Error) => Result;
  }
}

export const Error = {
  eventNotFoundError: (): Error.EventNotFoundError => {
    const valueWithoutVisit: Omit<Error.EventNotFoundError, "_visit"> = {
      errorName: "EventNotFoundError",
    };
    Object.defineProperty(valueWithoutVisit, "_visit", {
      enumerable: false,
      writable: true,
    });
    const castedValue = valueWithoutVisit as Error.EventNotFoundError;
    castedValue._visit = (visitor) => visitor.eventNotFoundError();
    return castedValue;
  },

  eventNotPublishedError: (): Error.EventNotPublishedError => {
    const valueWithoutVisit: Omit<Error.EventNotPublishedError, "_visit"> = {
      errorName: "EventNotPublishedError",
    };
    Object.defineProperty(valueWithoutVisit, "_visit", {
      enumerable: false,
      writable: true,
    });
    const castedValue = valueWithoutVisit as Error.EventNotPublishedError;
    castedValue._visit = (visitor) => visitor.eventNotPublishedError();
    return castedValue;
  },
} as const;
