/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../core";

export const EmailMessage: core.serialization.ObjectSchema<serializers.EmailMessage.Raw, RavenApi.EmailMessage> =
    core.serialization.object({
        text: core.serialization.string(),
        htmlBody: core.serialization.property("html_body", core.serialization.string()),
        subject: core.serialization.string(),
    });

export declare namespace EmailMessage {
    interface Raw {
        text: string;
        html_body: string;
        subject: string;
    }
}
