/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../core";

export const EventOverride: core.serialization.ObjectSchema<serializers.EventOverride.Raw, RavenApi.EventOverride> =
    core.serialization.object({
        email: core.serialization.lazyObject(async () => (await import("../../..")).EmailOverride).optional(),
        sms: core.serialization.lazyObject(async () => (await import("../../..")).SmsOverride).optional(),
        whatsapp: core.serialization.lazyObject(async () => (await import("../../..")).WhatsappOverride).optional(),
        push: core.serialization.lazyObject(async () => (await import("../../..")).PushOverride).optional(),
        webhook: core.serialization.lazyObject(async () => (await import("../../..")).WebhookOverride).optional(),
        voice: core.serialization.lazyObject(async () => (await import("../../..")).VoiceOverride).optional(),
        slack: core.serialization.lazyObject(async () => (await import("../../..")).SlackOverride).optional(),
        inApp: core.serialization.property(
            "in_app",
            core.serialization.lazyObject(async () => (await import("../../..")).InAppOverride).optional()
        ),
        telegram: core.serialization.lazyObject(async () => (await import("../../..")).TelegramOverride).optional(),
        providers: core.serialization.record(
            core.serialization.string(),
            core.serialization.lazyObject(async () => (await import("../../..")).ProviderOverride)
        ),
    });

export declare namespace EventOverride {
    interface Raw {
        email?: serializers.EmailOverride.Raw | null;
        sms?: serializers.SmsOverride.Raw | null;
        whatsapp?: serializers.WhatsappOverride.Raw | null;
        push?: serializers.PushOverride.Raw | null;
        webhook?: serializers.WebhookOverride.Raw | null;
        voice?: serializers.VoiceOverride.Raw | null;
        slack?: serializers.SlackOverride.Raw | null;
        in_app?: serializers.InAppOverride.Raw | null;
        telegram?: serializers.TelegramOverride.Raw | null;
        providers: Record<string, serializers.ProviderOverride.Raw>;
    }
}
