/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../core";

export const Param: core.serialization.ObjectSchema<serializers.Param.Raw, RavenApi.Param> = core.serialization.object({
    name: core.serialization.string(),
    value: core.serialization.string(),
});

export declare namespace Param {
    interface Raw {
        name: string;
        value: string;
    }
}
