/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../core";

export const PushOverride: core.serialization.ObjectSchema<serializers.PushOverride.Raw, RavenApi.PushOverride> =
    core.serialization
        .object({})
        .extend(core.serialization.lazyObject(async () => (await import("../../..")).ChannelOverride));

export declare namespace PushOverride {
    interface Raw extends serializers.ChannelOverride.Raw {}
}
