/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../core";

export const SlackOverride: core.serialization.ObjectSchema<serializers.SlackOverride.Raw, RavenApi.SlackOverride> =
    core.serialization
        .object({
            message: core.serialization.lazyObject(async () => (await import("../../..")).SlackMessage),
        })
        .extend(core.serialization.lazyObject(async () => (await import("../../..")).ChannelOverride));

export declare namespace SlackOverride {
    interface Raw extends serializers.ChannelOverride.Raw {
        message: serializers.SlackMessage.Raw;
    }
}
