/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../core";

export const SmsMessage: core.serialization.ObjectSchema<serializers.SmsMessage.Raw, RavenApi.SmsMessage> =
    core.serialization.object({
        text: core.serialization.string(),
    });

export declare namespace SmsMessage {
    interface Raw {
        text: string;
    }
}
