/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../core";

export const User: core.serialization.ObjectSchema<serializers.User.Raw, RavenApi.User> = core.serialization.object({
    userId: core.serialization.property(
        "user_id",
        core.serialization.lazy(async () => (await import("../../..")).UserId).optional()
    ),
    email: core.serialization.string().optional(),
    mobile: core.serialization.string().optional(),
    whatsappMobile: core.serialization.property("whatsapp_mobile", core.serialization.string().optional()),
    onesignalExternalId: core.serialization.property("onesignal_external_id", core.serialization.string().optional()),
    onesignalPlayerIds: core.serialization.property(
        "onesignal_player_ids",
        core.serialization.list(core.serialization.string()).optional()
    ),
    fcmTokens: core.serialization.property(
        "fcm_tokens",
        core.serialization.list(core.serialization.string()).optional()
    ),
    iosTokens: core.serialization.property(
        "ios_tokens",
        core.serialization.list(core.serialization.string()).optional()
    ),
    slack: core.serialization.lazyObject(async () => (await import("../../..")).SlackProfile).optional(),
    telegram: core.serialization.lazyObject(async () => (await import("../../..")).TelegramProfile).optional(),
    fcmTopic: core.serialization.property("fcm_topic", core.serialization.string().optional()),
    fcmDeviceGroup: core.serialization.property("fcm_device_group", core.serialization.string().optional()),
});

export declare namespace User {
    interface Raw {
        user_id?: serializers.UserId.Raw | null;
        email?: string | null;
        mobile?: string | null;
        whatsapp_mobile?: string | null;
        onesignal_external_id?: string | null;
        onesignal_player_ids?: string[] | null;
        fcm_tokens?: string[] | null;
        ios_tokens?: string[] | null;
        slack?: serializers.SlackProfile.Raw | null;
        telegram?: serializers.TelegramProfile.Raw | null;
        fcm_topic?: string | null;
        fcm_device_group?: string | null;
    }
}
