/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../core";

export const WhatsappOverride: core.serialization.ObjectSchema<
    serializers.WhatsappOverride.Raw,
    RavenApi.WhatsappOverride
> = core.serialization
    .object({
        message: core.serialization.lazyObject(async () => (await import("../../..")).SmsMessage),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).ChannelOverride));

export declare namespace WhatsappOverride {
    interface Raw extends serializers.ChannelOverride.Raw {
        message: serializers.SmsMessage.Raw;
    }
}
