/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";

export interface CreateUserRequest {
    userId: RavenApi.UserId;
    mobile?: string;
    email?: string;
    whatsApp?: string;
}
