/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";

export const BulkSendEventRequest: core.serialization.Schema<
    serializers.BulkSendEventRequest.Raw,
    Omit<RavenApi.BulkSendEventRequest, "idempotencyKey">
> = core.serialization.object({
    event: core.serialization.string(),
    batch: core.serialization.list(core.serialization.lazyObject(async () => (await import("../..")).BatchEvent)),
});

export declare namespace BulkSendEventRequest {
    interface Raw {
        event: string;
        batch: serializers.BatchEvent.Raw[];
    }
}
