/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../core";

export const ChannelPreference: core.serialization.ObjectSchema<
    serializers.ChannelPreference.Raw,
    RavenApi.ChannelPreference
> = core.serialization.object({
    disabled: core.serialization.boolean(),
});

export declare namespace ChannelPreference {
    interface Raw {
        disabled: boolean;
    }
}
