/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../core";

export const ChannelPreferences: core.serialization.ObjectSchema<
    serializers.ChannelPreferences.Raw,
    RavenApi.ChannelPreferences
> = core.serialization.object({
    sms: core.serialization.lazyObject(async () => (await import("../../..")).ChannelPreference).optional(),
    push: core.serialization.lazyObject(async () => (await import("../../..")).ChannelPreference).optional(),
    whatsapp: core.serialization.lazyObject(async () => (await import("../../..")).ChannelPreference).optional(),
    email: core.serialization.lazyObject(async () => (await import("../../..")).ChannelPreference).optional(),
    slack: core.serialization.lazyObject(async () => (await import("../../..")).ChannelPreference).optional(),
    voice: core.serialization.lazyObject(async () => (await import("../../..")).ChannelPreference).optional(),
    teams: core.serialization.lazyObject(async () => (await import("../../..")).ChannelPreference).optional(),
});

export declare namespace ChannelPreferences {
    interface Raw {
        sms?: serializers.ChannelPreference.Raw | null;
        push?: serializers.ChannelPreference.Raw | null;
        whatsapp?: serializers.ChannelPreference.Raw | null;
        email?: serializers.ChannelPreference.Raw | null;
        slack?: serializers.ChannelPreference.Raw | null;
        voice?: serializers.ChannelPreference.Raw | null;
        teams?: serializers.ChannelPreference.Raw | null;
    }
}
