/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../core";

export const Channel: core.serialization.Schema<serializers.Channel.Raw, RavenApi.Channel> = core.serialization.enum_([
    "VOICE",
    "PUSH",
    "SMS",
    "EMAIL",
    "WHATSAPP",
    "WEBHOOK",
    "SLACK",
    "IN_APP",
    "TELEGRAM",
]);

export declare namespace Channel {
    type Raw = "VOICE" | "PUSH" | "SMS" | "EMAIL" | "WHATSAPP" | "WEBHOOK" | "SLACK" | "IN_APP" | "TELEGRAM";
}
