/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../core";

export const RavenUser: core.serialization.ObjectSchema<serializers.RavenUser.Raw, RavenApi.RavenUser> =
    core.serialization.object({
        userId: core.serialization.property(
            "user_id",
            core.serialization.lazy(async () => (await import("../../..")).UserId)
        ),
        userSid: core.serialization.property("user_sid", core.serialization.string().optional()),
        onesignalExternalId: core.serialization.property(
            "onesignal_external_id",
            core.serialization.string().optional()
        ),
        mobile: core.serialization.string().optional(),
        email: core.serialization.string().optional(),
        whatsappMobile: core.serialization.property("whatsapp_mobile", core.serialization.string().optional()),
        slack: core.serialization.lazyObject(async () => (await import("../../..")).SlackProfile).optional(),
        telegram: core.serialization.lazyObject(async () => (await import("../../..")).TelegramProfile).optional(),
        fcmTokens: core.serialization.property(
            "fcm_tokens",
            core.serialization.list(core.serialization.string()).optional()
        ),
        onesignalPlayerIds: core.serialization.property(
            "onesignal_player_ids",
            core.serialization.list(core.serialization.string()).optional()
        ),
        iosTokens: core.serialization.property(
            "ios_tokens",
            core.serialization.list(core.serialization.string()).optional()
        ),
        createdAt: core.serialization.property("created_at", core.serialization.number().optional()),
        updatedAt: core.serialization.property("updated_at", core.serialization.number().optional()),
    });

export declare namespace RavenUser {
    interface Raw {
        user_id: serializers.UserId.Raw;
        user_sid?: string | null;
        onesignal_external_id?: string | null;
        mobile?: string | null;
        email?: string | null;
        whatsapp_mobile?: string | null;
        slack?: serializers.SlackProfile.Raw | null;
        telegram?: serializers.TelegramProfile.Raw | null;
        fcm_tokens?: string[] | null;
        onesignal_player_ids?: string[] | null;
        ios_tokens?: string[] | null;
        created_at?: number | null;
        updated_at?: number | null;
    }
}
