/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../core";

export const SlackProfile: core.serialization.ObjectSchema<serializers.SlackProfile.Raw, RavenApi.SlackProfile> =
    core.serialization.object({
        accessToken: core.serialization.property("access_token", core.serialization.string()),
        email: core.serialization.string().optional(),
        channelId: core.serialization.property("channel_id", core.serialization.string().optional()),
    });

export declare namespace SlackProfile {
    interface Raw {
        access_token: string;
        email?: string | null;
        channel_id?: string | null;
    }
}
