/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../core";

export const TelegramProfile: core.serialization.ObjectSchema<
    serializers.TelegramProfile.Raw,
    RavenApi.TelegramProfile
> = core.serialization.object({
    chatId: core.serialization.property("chat_id", core.serialization.string()),
});

export declare namespace TelegramProfile {
    interface Raw {
        chat_id: string;
    }
}
