/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../core";

export const UserPreferences: core.serialization.ObjectSchema<
    serializers.UserPreferences.Raw,
    RavenApi.UserPreferences
> = core.serialization.object({
    preferredChannel: core.serialization.property(
        "preferred_channel",
        core.serialization.lazy(async () => (await import("../../..")).Channel).optional()
    ),
    channelPreferences: core.serialization.property(
        "channel_preferences",
        core.serialization.lazyObject(async () => (await import("../../..")).ChannelPreferences).optional()
    ),
});

export declare namespace UserPreferences {
    interface Raw {
        preferred_channel?: serializers.Channel.Raw | null;
        channel_preferences?: serializers.ChannelPreferences.Raw | null;
    }
}
