/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";

export interface EventOverride {
    email?: RavenApi.EmailOverride;
    sms?: RavenApi.SmsOverride;
    whatsapp?: RavenApi.WhatsappOverride;
    push?: RavenApi.PushOverride;
    webhook?: RavenApi.WebhookOverride;
    voice?: RavenApi.VoiceOverride;
    slack?: RavenApi.SlackOverride;
    inApp?: RavenApi.InAppOverride;
    telegram?: RavenApi.TelegramOverride;
    providers: Record<string, RavenApi.ProviderOverride>;
}
