/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";

export interface SendEventResponse {
    id: RavenApi.RequestId;
    success: boolean;
}
