/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";

export type AppId = string;

export function AppId(value: string): RavenApi.AppId {
  return value as unknown as RavenApi.AppId;
}
