/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";

export type DeviceId = string;

export function DeviceId(value: string): RavenApi.DeviceId {
  return value as unknown as RavenApi.DeviceId;
}
