/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";

export type RequestId = string;

export function RequestId(value: string): RavenApi.RequestId {
  return value as unknown as RavenApi.RequestId;
}
