/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";

export type UserId = string;

export function UserId(value: string): RavenApi.UserId {
  return value as unknown as RavenApi.UserId;
}
