/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";

export const Attachment: core.schemas.ObjectSchema<Attachment.Raw, RavenApi.event.Attachment> = core.schemas.object({
  fileName: core.schemas.property("file_name", core.schemas.string()),
  content: core.schemas.string(),
  url: core.schemas.string(),
});

export declare namespace Attachment {
  interface Raw {
    file_name: string;
    content: string;
    url: string;
  }
}
