/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const BatchEvent: core.schemas.ObjectSchema<BatchEvent.Raw, RavenApi.event.BatchEvent> = core.schemas.object({
  data: core.schemas.record(core.schemas.string(), core.schemas.unknown()),
  user: core.schemas.lazyObject(() => schemas.event.User).optional(),
  override: core.schemas.lazyObject(() => schemas.event.EventOverride).optional(),
});

export declare namespace BatchEvent {
  interface Raw {
    data: Record<string, unknown>;
    user?: schemas.event.User.Raw | null;
    override?: schemas.event.EventOverride.Raw | null;
  }
}
