/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const EmailOverride: core.schemas.ObjectSchema<EmailOverride.Raw, RavenApi.event.EmailOverride> = core.schemas
  .object({
    from: core.schemas.lazyObject(() => schemas.event.EmailRecipient),
    cc: core.schemas.list(core.schemas.lazyObject(() => schemas.event.EmailRecipient)),
    bcc: core.schemas.list(core.schemas.lazyObject(() => schemas.event.EmailRecipient)),
    attachments: core.schemas.list(core.schemas.lazyObject(() => schemas.event.Attachment)),
    message: core.schemas.lazyObject(() => schemas.event.EmailMessage),
  })
  .extend(core.schemas.lazyObject(() => schemas.event.ChannelOverride));

export declare namespace EmailOverride {
  interface Raw extends schemas.event.ChannelOverride.Raw {
    from: schemas.event.EmailRecipient.Raw;
    cc: schemas.event.EmailRecipient.Raw[];
    bcc: schemas.event.EmailRecipient.Raw[];
    attachments: schemas.event.Attachment.Raw[];
    message: schemas.event.EmailMessage.Raw;
  }
}
