/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const PushOverride: core.schemas.ObjectSchema<PushOverride.Raw, RavenApi.event.PushOverride> = core.schemas
  .object({})
  .extend(core.schemas.lazyObject(() => schemas.event.ChannelOverride));

export declare namespace PushOverride {
  interface Raw extends schemas.event.ChannelOverride.Raw {}
}
