/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const SendEventResponse: core.schemas.ObjectSchema<SendEventResponse.Raw, RavenApi.event.SendEventResponse> =
  core.schemas.object({
    id: core.schemas.lazy(() => schemas.ids.RequestId),
    success: core.schemas.boolean(),
  });

export declare namespace SendEventResponse {
  interface Raw {
    id: schemas.ids.RequestId.Raw;
    success: boolean;
  }
}
