/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";

export const SlackMessage: core.schemas.ObjectSchema<SlackMessage.Raw, RavenApi.event.SlackMessage> =
  core.schemas.object({
    text: core.schemas.string(),
    blocks: core.schemas.unknown(),
  });

export declare namespace SlackMessage {
  interface Raw {
    text: string;
    blocks?: unknown;
  }
}
