/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const TelegramOverride: core.schemas.ObjectSchema<TelegramOverride.Raw, RavenApi.event.TelegramOverride> =
  core.schemas.object({}).extend(core.schemas.lazyObject(() => schemas.event.ChannelOverride));

export declare namespace TelegramOverride {
  interface Raw extends schemas.event.ChannelOverride.Raw {}
}
