/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const WhatsappOverride: core.schemas.ObjectSchema<WhatsappOverride.Raw, RavenApi.event.WhatsappOverride> =
  core.schemas
    .object({
      message: core.schemas.lazyObject(() => schemas.event.SmsMessage),
    })
    .extend(core.schemas.lazyObject(() => schemas.event.ChannelOverride));

export declare namespace WhatsappOverride {
  interface Raw extends schemas.event.ChannelOverride.Raw {
    message: schemas.event.SmsMessage.Raw;
  }
}
