/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";

export interface SmsOverride extends RavenApi.ChannelOverride {
    sender: string;
    message: RavenApi.SmsMessage;
}
