/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";

export interface WhatsappOverride extends RavenApi.ChannelOverride {
    message: RavenApi.SmsMessage;
}
