/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../../core";

export const CreateUserRequest: core.serialization.Schema<
    serializers.CreateUserRequest.Raw,
    RavenApi.CreateUserRequest
> = core.serialization.object({
    userId: core.serialization.property(
        "user_id",
        core.serialization.lazy(async () => (await import("../../../..")).UserId)
    ),
    mobile: core.serialization.string().optional(),
    email: core.serialization.string().optional(),
    whatsApp: core.serialization.property("whats_app", core.serialization.string().optional()),
});

export declare namespace CreateUserRequest {
    interface Raw {
        user_id: serializers.UserId.Raw;
        mobile?: string | null;
        email?: string | null;
        whats_app?: string | null;
    }
}
