/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../../core";

export const SendEventRequest: core.serialization.Schema<
    serializers.SendEventRequest.Raw,
    Omit<RavenApi.SendEventRequest, "idempotencyKey">
> = core.serialization.object({
    event: core.serialization.string(),
    data: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    user: core.serialization.lazyObject(async () => (await import("../../../..")).User).optional(),
    scheduleAt: core.serialization.number().optional(),
    override: core.serialization.lazyObject(async () => (await import("../../../..")).EventOverride).optional(),
});

export declare namespace SendEventRequest {
    interface Raw {
        event: string;
        data: Record<string, unknown>;
        user?: serializers.User.Raw | null;
        scheduleAt?: number | null;
        override?: serializers.EventOverride.Raw | null;
    }
}
