/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";

export const Channel: core.schemas.Schema<Channel.Raw, RavenApi.user.Channel> = core.schemas
  .string()
  .transform<RavenApi.user.Channel>({
    parse: (value) => RavenApi.user.Channel._parse(value),
    json: ({ value }) => value,
  });

export declare namespace Channel {
  type Raw = string;
}
