/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const ChannelPreferences: core.schemas.ObjectSchema<ChannelPreferences.Raw, RavenApi.user.ChannelPreferences> =
  core.schemas.object({
    sms: core.schemas.lazyObject(() => schemas.user.ChannelPreference).optional(),
    push: core.schemas.lazyObject(() => schemas.user.ChannelPreference).optional(),
    whatsapp: core.schemas.lazyObject(() => schemas.user.ChannelPreference).optional(),
    email: core.schemas.lazyObject(() => schemas.user.ChannelPreference).optional(),
    slack: core.schemas.lazyObject(() => schemas.user.ChannelPreference).optional(),
    voice: core.schemas.lazyObject(() => schemas.user.ChannelPreference).optional(),
    teams: core.schemas.lazyObject(() => schemas.user.ChannelPreference).optional(),
  });

export declare namespace ChannelPreferences {
  interface Raw {
    sms?: schemas.user.ChannelPreference.Raw | null;
    push?: schemas.user.ChannelPreference.Raw | null;
    whatsapp?: schemas.user.ChannelPreference.Raw | null;
    email?: schemas.user.ChannelPreference.Raw | null;
    slack?: schemas.user.ChannelPreference.Raw | null;
    voice?: schemas.user.ChannelPreference.Raw | null;
    teams?: schemas.user.ChannelPreference.Raw | null;
  }
}
