/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const CreateUserRequest: core.schemas.ObjectSchema<CreateUserRequest.Raw, RavenApi.user.CreateUserRequest> =
  core.schemas.object({
    userId: core.schemas.property(
      "user_id",
      core.schemas.lazy(() => schemas.ids.UserId)
    ),
    mobile: core.schemas.string().optional(),
    email: core.schemas.string().optional(),
    whatsApp: core.schemas.property("whats_app", core.schemas.string().optional()),
  });

export declare namespace CreateUserRequest {
  interface Raw {
    user_id: schemas.ids.UserId.Raw;
    mobile?: string | null;
    email?: string | null;
    whats_app?: string | null;
  }
}
