/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const UserPreferences: core.schemas.ObjectSchema<UserPreferences.Raw, RavenApi.user.UserPreferences> =
  core.schemas.object({
    preferredChannel: core.schemas.property(
      "preferred_channel",
      core.schemas.lazy(() => schemas.user.Channel).optional()
    ),
    channelPreferences: core.schemas.property(
      "channel_preferences",
      core.schemas.lazyObject(() => schemas.user.ChannelPreferences).optional()
    ),
  });

export declare namespace UserPreferences {
  interface Raw {
    preferred_channel?: schemas.user.Channel.Raw | null;
    channel_preferences?: schemas.user.ChannelPreferences.Raw | null;
  }
}
