/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";

export interface Request {
  /** your app identifier */
  appId: RavenApi.ids.AppId;
  /** your user identifier */
  userId: RavenApi.ids.UserId;
  /** your device identifier */
  deviceId: RavenApi.ids.DeviceId;
}

export type Response = core.APIResponse<RavenApi.device.Device, RavenApi.device.getDevice.Error>;
export type Error = Error._Unknown;

export declare namespace Error {
  interface _Unknown extends _Utils {
    errorName: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <Result>(visitor: Error._Visitor<Result>) => Result;
  }

  interface _Visitor<Result> {
    _other: (value: core.Fetcher.Error) => Result;
  }
}
