/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";

export interface Request {
  /** your app identifier */
  appId: RavenApi.AppId;
  /** your user identifier */
  userId: RavenApi.UserId;
  /** your device identifier; the same as device_sid */
  deviceId: RavenApi.DeviceId;
  _body: RavenApi.Device;
}

export type Response = core.APIResponse<RavenApi.Device, RavenApi.device.update.Error>;
export type Error = RavenApi.device.update.Error._Unknown;

export declare namespace Error {
  interface _Unknown extends _Utils {
    errorName: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <_Result>(visitor: RavenApi.device.update.Error._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    _other: (value: core.Fetcher.Error) => _Result;
  }
}
