/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";

export interface ChannelPreferences {
    sms?: RavenApi.ChannelPreference;
    push?: RavenApi.ChannelPreference;
    whatsapp?: RavenApi.ChannelPreference;
    email?: RavenApi.ChannelPreference;
    slack?: RavenApi.ChannelPreference;
    voice?: RavenApi.ChannelPreference;
    teams?: RavenApi.ChannelPreference;
}
