/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Channel = "VOICE" | "PUSH" | "SMS" | "EMAIL" | "WHATSAPP" | "WEBHOOK" | "SLACK" | "IN_APP" | "TELEGRAM";

export const Channel = {
    Voice: "VOICE",
    Push: "PUSH",
    Sms: "SMS",
    Email: "EMAIL",
    Whatsapp: "WHATSAPP",
    Webhook: "WEBHOOK",
    Slack: "SLACK",
    InApp: "IN_APP",
    Telegram: "TELEGRAM",
} as const;
