/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";

export interface ChannelPreferences {
  sms?: RavenApi.user.ChannelPreference;
  push?: RavenApi.user.ChannelPreference;
  whatsapp?: RavenApi.user.ChannelPreference;
  email?: RavenApi.user.ChannelPreference;
  slack?: RavenApi.user.ChannelPreference;
  voice?: RavenApi.user.ChannelPreference;
  teams?: RavenApi.user.ChannelPreference;
}
