/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";

export interface CreateUserRequest {
  /**
   * Your user identifier.
   *   if user_id already exists, user properties will be updated else a new user will be created
   *
   */
  userId: RavenApi.ids.UserId;
  mobile?: string;
  email?: string;
  /** include this only when user's whatsapp mobile is different than primary mobile */
  whatsApp?: string;
}
