/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";

export interface Device {
  id?: string;
  platform?: RavenApi.Platform;
  onesignalPlayerId?: string;
  xiaomiToken?: string;
  oppoToken?: string;
  vivoToken?: string;
  huaweiToken?: string;
  /** firebase device token */
  fcmToken?: string;
  /** user id affiliated with device */
  ravenId?: string;
  deviceSid?: RavenApi.DeviceId;
  notificationsDisabled?: boolean;
  createdAt?: number;
  updatedAt?: number;
}
