/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";

export const AppId: core.schemas.Schema<AppId.Raw, RavenApi.ids.AppId> = core.schemas.string();

export declare namespace AppId {
  type Raw = string;
}
