/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "../../..";
import * as core from "../../../core";

export const DeviceId: core.schemas.Schema<DeviceId.Raw, RavenApi.ids.DeviceId> = core.schemas.string();

export declare namespace DeviceId {
  type Raw = string;
}
