/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../core";

export const Attachment: core.serialization.ObjectSchema<serializers.Attachment.Raw, RavenApi.Attachment> =
    core.serialization.object({
        fileName: core.serialization.property("file_name", core.serialization.string()),
        content: core.serialization.string(),
        url: core.serialization.string(),
    });

export declare namespace Attachment {
    interface Raw {
        file_name: string;
        content: string;
        url: string;
    }
}
