/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../core";

export const ChannelOverride: core.serialization.ObjectSchema<
    serializers.ChannelOverride.Raw,
    RavenApi.ChannelOverride
> = core.serialization.object({
    scheduleAt: core.serialization.property("schedule_at", core.serialization.number()),
});

export declare namespace ChannelOverride {
    interface Raw {
        schedule_at: number;
    }
}
