/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../core";

export const EmailRecipient: core.serialization.ObjectSchema<serializers.EmailRecipient.Raw, RavenApi.EmailRecipient> =
    core.serialization.object({
        name: core.serialization.string(),
        address: core.serialization.string(),
    });

export declare namespace EmailRecipient {
    interface Raw {
        name: string;
        address: string;
    }
}
