/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../core";

export const EventNotFoundErrorBody: core.serialization.ObjectSchema<
    serializers.EventNotFoundErrorBody.Raw,
    RavenApi.EventNotFoundErrorBody
> = core.serialization.object({
    success: core.serialization.boolean(),
    error: core.serialization.string(),
});

export declare namespace EventNotFoundErrorBody {
    interface Raw {
        success: boolean;
        error: string;
    }
}
