/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../core";

export const InAppOverride: core.serialization.ObjectSchema<serializers.InAppOverride.Raw, RavenApi.InAppOverride> =
    core.serialization
        .object({})
        .extend(core.serialization.lazyObject(async () => (await import("..")).ChannelOverride));

export declare namespace InAppOverride {
    interface Raw extends serializers.ChannelOverride.Raw {}
}
