/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../core";

export const SendEventResponse: core.serialization.ObjectSchema<
    serializers.SendEventResponse.Raw,
    RavenApi.SendEventResponse
> = core.serialization.object({
    id: core.serialization.lazy(async () => (await import("..")).RequestId),
    success: core.serialization.boolean(),
});

export declare namespace SendEventResponse {
    interface Raw {
        id: serializers.RequestId.Raw;
        success: boolean;
    }
}
