/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../core";

export const SmsOverride: core.serialization.ObjectSchema<serializers.SmsOverride.Raw, RavenApi.SmsOverride> =
    core.serialization
        .object({
            sender: core.serialization.string(),
            message: core.serialization.lazyObject(async () => (await import("..")).SmsMessage),
        })
        .extend(core.serialization.lazyObject(async () => (await import("..")).ChannelOverride));

export declare namespace SmsOverride {
    interface Raw extends serializers.ChannelOverride.Raw {
        sender: string;
        message: serializers.SmsMessage.Raw;
    }
}
