/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../core";

export const TelegramOverride: core.serialization.ObjectSchema<
    serializers.TelegramOverride.Raw,
    RavenApi.TelegramOverride
> = core.serialization
    .object({})
    .extend(core.serialization.lazyObject(async () => (await import("..")).ChannelOverride));

export declare namespace TelegramOverride {
    interface Raw extends serializers.ChannelOverride.Raw {}
}
