/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../core";

export const WebhookOverride: core.serialization.ObjectSchema<
    serializers.WebhookOverride.Raw,
    RavenApi.WebhookOverride
> = core.serialization
    .object({})
    .extend(core.serialization.lazyObject(async () => (await import("..")).ChannelOverride));

export declare namespace WebhookOverride {
    interface Raw extends serializers.ChannelOverride.Raw {}
}
