/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../core";

export const Device: core.serialization.ObjectSchema<serializers.Device.Raw, RavenApi.Device> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        platform: core.serialization.lazy(async () => (await import("../../..")).Platform).optional(),
        onesignalPlayerId: core.serialization.property("onesignal_player_id", core.serialization.string().optional()),
        xiaomiToken: core.serialization.property("xiaomi_token", core.serialization.string().optional()),
        oppoToken: core.serialization.property("oppo_token", core.serialization.string().optional()),
        vivoToken: core.serialization.property("vivo_token", core.serialization.string().optional()),
        huaweiToken: core.serialization.string().optional(),
        fcmToken: core.serialization.property("fcm_token", core.serialization.string().optional()),
        ravenId: core.serialization.property("raven_id", core.serialization.string().optional()),
        deviceSid: core.serialization.property(
            "device_sid",
            core.serialization.lazy(async () => (await import("../../..")).DeviceId).optional()
        ),
        notificationsDisabled: core.serialization.property(
            "notifications_disabled",
            core.serialization.boolean().optional()
        ),
        createdAt: core.serialization.property("created_at", core.serialization.number().optional()),
        updatedAt: core.serialization.property("updated_at", core.serialization.number().optional()),
    });

export declare namespace Device {
    interface Raw {
        id?: string | null;
        platform?: serializers.Platform.Raw | null;
        onesignal_player_id?: string | null;
        xiaomi_token?: string | null;
        oppo_token?: string | null;
        vivo_token?: string | null;
        huaweiToken?: string | null;
        fcm_token?: string | null;
        raven_id?: string | null;
        device_sid?: serializers.DeviceId.Raw | null;
        notifications_disabled?: boolean | null;
        created_at?: number | null;
        updated_at?: number | null;
    }
}
