/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../../core";

export const Platform: core.serialization.Schema<serializers.Platform.Raw, RavenApi.Platform> =
    core.serialization.enum_(["android", "web", "ios"]);

export declare namespace Platform {
    type Raw = "android" | "web" | "ios";
}
