/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const RavenApiEnvironment = {
    Prod: "https://api.ravenapp.dev",
} as const;

export type RavenApiEnvironment = typeof RavenApiEnvironment.Prod;
