/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RavenApi } from "@ravenapp/raven";
import * as core from "../../../core";

export const Platform: core.schemas.Schema<Platform.Raw, RavenApi.Platform> = core.schemas
  .string()
  .transform<RavenApi.Platform>({
    parse: (value) => RavenApi.Platform._parse(value),
    json: ({ value }) => value,
  });

export declare namespace Platform {
  type Raw = string;
}
